### ISSUE TITLE
undefined in prismic api url 

### ISSUE THREAD

**Issue by zilahir** [littleplusbig/gatsby-theme-legals-prismic#26]
When trying to `gatsby develop`, 

getting the following issue: 

```
 ERROR #11321  PLUGIN

"gatsby-source-prismic" threw an error while running the sourceNodes lifecycle:

Unexpected status code [404] on URL https://undefined.prismic.io/api/v2



  Error: Unexpected status code [404] on URL https://undefined.prismic.io/api/v2

  - prismic-javascript.min.js:1
    [legal]/[prismic-javascript]/dist/prismic-javascript.min.js:1:14909

  - next_tick.js:68 process._tickCallback
    internal/process/next_tick.js:68:7


```

In the `gatsby-config.js` has the correct value for the repo url: 

```
repositoryName: "my-legal-repo-name",
```

**Comment by zilahir** [comment]
it seems like the 

`const apiEndpoint = `https://${repositoryName}.prismic.io/api/v2`;`

`repositoryName` var is not getting there.

**Comment by AllanPooley** [comment]
Hey @zilahir can you send me a snippet of how you've configured the theme in your `gatsby-config`?

Does it look similar to this?

```
   {
      resolve: '@littleplusbig/gatsby-theme-legals-prismic',
      options: {
        prismicRepositoryName: 'my-prismic-repo-name-kebab-case',
        prismicAccessToken: 'MC5YVDQya-XXXXX',
        siteName: 'Gatsby Theme Legals Prismic Demo',
      },
    },
```

**Comment by AllanPooley** [comment]
My apologies @zilahir, I had forgotten to update the theme parameters / options / arguments.

I've now updated this.

`repositoryName` should be `prismicRepositoryName`
and
`accessToken` should be `prismicAccessToken`
