### ISSUE TITLE
Can't Find Plug-in

### ISSUE THREAD

**Issue by weisisheng** [littleplusbig/gatsby-theme-legals-prismic#32]
Hey Gang-  Thanks for the amazing work.  Kinda a noob at Gatsby although I have set up a few toy sites locally while learning.  I do a yarn install of this theme and no errors surface after I manually add the peer Dependency below:

  "peerDependencies": {
    "graphql-tag-pluck": "^0.8.3"
  },

The install shows up in my package.json

"dependencies": {
    "@littleplusbig/gatsby-theme-legals-prismic": "^1.0.18",
...

However, once I add my prismic particulars to gatsby-config.json:

`gatsby-theme-legals-prismic`,
    {
      resolve: `gatsby-theme-legals-prismic`,
      options: {
        prismicRepositoryName: 'foo-repo',
        prismicAccessToken: 'foo-token',
        siteName: 'foo.cn', // (Optional)
        homePath: '/' // (Optional) Defaults to '/'
      }
    },

---
 I get the following:

ERROR 

UNHANDLED REJECTION Unable to find plugin "gatsby-theme-legals-prismic". Perhaps you need to install its package?

  Error: Unable to find plugin "gatsby-theme-legals-prismic". Perhaps you need to install its package?

Thanks in advance for any advice.
  
$ gatsby -version
2.1.0
$ yarn -version
1.19.1

**Comment by weisisheng** [comment]
Believe this is related to requiring the full name to be resolved in gatsby-config.json and documents need to be expanded.  I can issue a PR?
{
resolve: '@littleplusbig/gatsby-theme-legals-prismic'
options: {
prismicRepositoryName: 'foo-repo',
prismicAccessToken: 'foo-token',
siteName: 'foo.cn', // (Optional)
homePath: '/' // (Optional) Defaults to '/'
}
},

**Comment by kenjwho** [comment]
@weisisheng Thanks for submitting this issue, and commenting with the fix!

**Comment by weisisheng** [comment]
Issued: https://github.com/littleplusbig/gatsby-theme-legals-prismic/pull/33
